---
- name: Накатка Jellyfin сервиса на контейнер
  hosts: media_lxc
  become: true
  environment:
    # DEBIAN_FRONTEND: noninteractive # apt молчит
    # NEEDRESTART_MODE: a
    SKIP_CONFIRM: "1"

  vars:
    media_gid: 1000

  tasks:
    - name: Создание группы media
      ansible.builtin.group:
        name: media
        gid: "{{ media_gid }}"
        state: present

    - name: Установка curl
      ansible.builtin.apt:
        name: curl
        state: present
        update_cache: true

    - name: Скачивание установщика Jellyfin
      ansible.builtin.get_url:
        url: https://repo.jellyfin.org/install-debuntu.sh
        dest: /tmp/install-jellyfin.sh
        mode: "0755"

    - name: Установка Jellyfin
      ansible.builtin.command: /tmp/install-jellyfin.sh
      args:
        creates: /usr/bin/jellyfin

    - name: Запуск сервиса через systemd
      ansible.builtin.systemd:
        name: jellyfin
        enabled: true
        state: started

    - name: Добавить юзера jellyfin в группу media
      ansible.builtin.user:
        name: jellyfin
        groups: media
        append: true
      notify: Перезапустить jellyfin

  handlers:
    - name: Перезапустить jellyfin
      ansible.builtin.systemd:
        name: jellyfin
        state: restarted
