---
- name: Накатка Prowlarr сервиса на контейнер
  hosts: prowlarr_lxc
  become: true
  environment:
    DEBIAN_FRONTEND: noninteractive
  # NEEDRESTART_MODE: a
  # SKIP_CONFIRM: "1"

  vars:
    app: prowlarr
    app_bin: Prowlarr
    install_dir: /opt/Prowlarr
    data_dir: /var/lib/prowlarr

  tasks:
    - name: Установка зависимостей Prowlarr
      ansible.builtin.apt:
        name: [curl, sqlite3, libsqlite3-0]
        state: present
        update_cache: true

    - name: Группа prowlarr
      ansible.builtin.group:
        name: "{{ app }}"

    - name: Юзер prowlarr
      ansible.builtin.user:
        name: "{{ app }}"
        group: "{{ app }}"
        system: true
        create_home: false
        shell: /usr/sbin/nologin

    - name: Скачать тарбол Prowlarr (через curl — servarr режет Python-клиент)
      ansible.builtin.command:
        cmd: >
          curl -fsSL
          -o /tmp/prowlarr.tar.gz
          "http://prowlarr.servarr.com/v1/update/master/updatefile?os=linux&runtime=netcore&arch=x64"
        creates: /opt/Prowlarr/Prowlarr

    - name: Распаковать в /opt
      ansible.builtin.unarchive:
        src: /tmp/prowlarr.tar.gz
        dest: /opt
        remote_src: true
        owner: prowlarr
        group: prowlarr
        creates: /opt/Prowlarr/Prowlarr

    - name: Каталог данных prowlarr
      ansible.builtin.file:
        path: "{{ data_dir }}"
        state: directory
        owner: "{{ app }}"
        group: "{{ app }}"
        mode: "0750"

    - name: Создание systemd-сервиса
      ansible.builtin.copy:
        dest: "/etc/systemd/system/{{ app }}.service"
        content: |
          [Unit]
          Description=Prowlarr Daemon
          After=network.target

          [Service]
          User={{ app }}
          Group={{ app }}
          Type=simple
          ExecStart={{ install_dir }}/{{ app_bin }} -nobrowser -data={{ data_dir }}
          Restart=on-failure
          TimeoutStopSec=20
          KillMode=process

          [Install]
          WantedBy=multi-user.target
      notify: reload systemd

    - name: Включение и запуск сервиса
      ansible.builtin.systemd:
        name: "{{ app }}"
        enabled: true
        state: started
        daemon_reload: true

  handlers:
    - name: reload systemd
      ansible.builtin.systemd:
        daemon_reload: true
