[proxmox]

glass ansible_host=192.168.1.122 ansible_user=root ansible_ssh_private_key_file=../.ssh/id_proxmox

[media_lxc]

jellyfin ansible_host=192.168.1.175 ansible_user=root ansible_ssh_private_key_file=../.ssh/id_proxmox

[prowlarr_lxc]

prowlarr ansible_host=192.168.1.176 ansible_user=root ansible_ssh_private_key_file=../.ssh/id_proxmox


[k3s_server]
k3s-master ansible_host=192.168.1.200

[k3s_agents]
k3s-worker-1 ansible_host=192.168.1.201
k3s-worker-2 ansible_host=192.168.1.202

[k3s_cluster:children]
k3s_server
k3s_agents

[k3s_cluster:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=../.ssh/id_proxmox

[media_storage]
media-storage ansible_host=192.168.1.205

[media_storage:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=../.ssh/id_proxmox

[proxy_xray]
proxy-xray ansible_host=192.168.1.177

[proxy_xray:vars]
ansible_user=root
ansible_ssh_private_key_file=../.ssh/id_proxmox